name: Migrate Work Items

on:
  workflow_dispatch:
    inputs: 
      ado-org:
        description: 'ado-org'
        required: true
        default: 'POCHCLTEAM'
      ado-project:
        description: 'ado-project'
        required: true
        default: 'DemoHCLProject'
      ado_area_path:
        description: 'ADO area path to migrate - uses the UNDER operator'
        required: true
        default: 'migrate'
      ado_migrate_closed_workitems:
        description: 'Migrate closed work items'
        required: true
        type: boolean
        default: 'true'
      ado_production_run:
        description: tag migrated work items with migrated-to-github and add discussion comment
        required: true
        type: boolean
        default: 'true'
      gh-org:
        description: 'devidayalhclteam'
        required: true
        default: 'devidayalhclteam'
      gh-repo:
        description: 'MigrationPipelinePoc'
        required: true
        default: 'migrate-ado-workitems'
      gh_update_assigned_to:
        description: 'Update Assigned To'
        required: true
        type: boolean
        default: 'true'
      gh_assigned_to_user_suffix:
        description: 'EMU suffix'
        required: true
        default: '_corp'
      gh_add_ado_comments:
        description: 'Add ADO Comments'
        required: true
        type: boolean
        default: 'true'

jobs:
  migrate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        id: get_installation_token
        with: 
          app_id: 363216
          installation_id: 39793963
          private_key: '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA3JSoTukcrFcgBNYSek5/MwjU1hr9Y2TkpfWojSl+0Z7Meiv8\njA/URMqN57Sj9wX2/0u3i7yE5Mac8uvRmIlPIn4eLEVmCMt7Psma6IOqVjR3qOa4\npKFK1AXMa3uajkj7xwwlzjgvgiQYwWLohVaU3udVqynX27YDrLwLIzGDEudTxsOa\nKjd6CFiBlW6P5PALiXEdV+yI8yC5QbJCjQMu3MBbc5f7Pmd1Ln0T1trww2TAq7+k\nhLBoQQQjtf8JgSgkJX8LXzMALJYg0Ynk7CrSom4jdwW3LO/ZrL9TVAHjx1E2bA+W\n4ue5aoo5n+8H2m/cVd92YU5yV/7ipYnLUg/bEwIDAQABAoIBAGIijSLWWVhfRrKA\nHyZk5/hnlHFQ/qyKxaMEQSHUdUSDVst/6FLT9AdK6olMd6o98B6yrA0yKRmzNz5o\nJg6sABYDcB8YHQYKqWFMxmttsIm7vATb6QftbmIX1lN3YVKuK73prKQroQ9QSec3\nvuUbmQ32c8m7yvpH5yihXH8i1wLALnk4mpOADK5BoBiAlIo5K5VT4/DIcXPnyI3h\nfIsIbSUSx+viM6o+Q5rIckvpG4mib+bdUyb3jB0kMnL8AViBDRnNn8rUiBrjqIez\nQD0h/MfGJVhImBHLiiNp6lNxE1P7WOhyVo7eqLbaAHJjE3ixlMmP3EW7DHqCPIQy\nk4HzjUECgYEA+To9BfFoyM5w/KZO5Y/IAzU9lHl+tJdMIDzo5Yh0IpXjfudi5Q8Q\nTk8U55TzJ2xl+j4FYtIBmbGHsV9HAMN4JD3n2cmuYg6o4GbMDj0e2Rs/bFYI+T0y\n8NYj/nh7jihM6nbSfUD0o96nmEGPpWp/I/BO97Dcb0cLuSEF4dWMnyECgYEA4pMi\n6xu/qwQY9ycU8c3SvGvFhuntcg3ey84zXHgIyCXisQclA6wzwsMZfn8/g0k6csvE\nyuR8Zl7OiPIfMCZwVsRZke6vdwHA7116EN/loguzUcblS80YY7TvTmIsD1qYwDUq\nAON7YW2NfNBZxDtEsEGhehnSG5oADRNCtId8t7MCgYEAvDXy544Lp7nfMa0WX95Z\nGbMXMg0eVpr7bk0RRGXr7kJrbuamlHzvv3ORQeIGTntZ98TmpF4bv0mGQ7jEEhuL\nmzL06E+aVYrklbKL3yThKuuc1d+TH0XMNnxA6mdqR0y/6UCabOSk2yvGPQElzbHD\nGgzcVclGbvKkM8Zwfr+aVoECgYB4lla/SsV3/3ZKFELRbvn5zmISq+30Be3OCrDL\nRhdmbsN39JV+nuftgGjRKmhjN1YkQs86LOEImuzRdgujVNH1XAtP3/kDHavRua59\nzKwq0o9dtr3S2hVg+6thzF4mzdD+e00fq/K+p8/l3f3osqKcLFIE6jko942PZ/DY\npEN8gQKBgByjoFE0QGFxkCIB0Gq0xZmWla0/580pn1WrmY5sn14hLk3h9TjxOfvJ\n07HJ260ayVCo6+plQa1Lha2HnRJAOjIwM7y/ttEM72FDLKSsR+8gUgm1E2mU02Nt\nLTvJa9cR+VfXZ8R8T6nS53qC9/fG9KfeXNowLj9MRglMLJaVEHw3\n-----END RSA PRIVATE'
      - name: run migration
        shell: pwsh
        run: |
          # run migration script
          
          # cleaning up bools
          $ado_migrate_closed_workitems=$false
          $ado_production_run=$false
          $gh_update_assigned_to=$false
          $gh_add_ado_comments=$false
          
          if("${{ github.event.inputs.ado_migrate_closed_workitems }}" -eq "true") {
            $ado_migrate_closed_workitems=$true
          }

          if("${{ github.event.inputs.ado_production_run }}" -eq "true") {
            $ado_production_run=$true
          }

          if("${{ github.event.inputs.gh_update_assigned_to }}" -eq "true") {
            $gh_update_assigned_to=$true
          }
          
          if("${{ github.event.inputs.gh_add_ado_comments }}" -eq "true") {
            $gh_add_ado_comments=$true
          }
          
          ./ado_workitems_to_github_issues.ps1 -ado_pat "${yz6gqrp6meew7qmvxznsqoee6dlmhp54lj2csoqcpcaabzxilxkq}" -ado_org "${{ github.event.inputs.ado-org }}" -ado_project "${{ github.event.inputs.ado-project }}" -ado_area_path "${{ github.event.inputs.ado_area_path }}" -ado_migrate_closed_workitems $ado_migrate_closed_workitems -ado_production_run $ado_production_run -gh_pat "${{ steps.get_installation_token.outputs.token }}" -gh_org "${{ github.event.inputs.gh-org }}" -gh_repo "${{ github.event.inputs.gh-repo }}" -gh_update_assigned_to $gh_update_assigned_to -gh_assigned_to_user_suffix "${{ github.event.inputs.gh_assigned_to_user_suffix }}" -gh_add_ado_comments $gh_add_ado_comments
          
